// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaborByte.Infraestructura.Persistencia;

#nullable disable

namespace SaborByte.Infraestructura.Persistencia.Migraciones.SaborByte
{
    [DbContext(typeof(SaborByteDbContext))]
    [Migration("20260824203548_AgregaActivoAMesa")]
    partial class AgregaActivoAMesa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaborByte.Dominio.Caja.Caja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ActualizadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoSucursal")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HostnamePermitido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpPermitida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ProximoNumeroFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId", "Numero")
                        .IsUnique();

                    b.ToTable("Cajas", "caja");
                });

            modelBuilder.Entity("SaborByte.Dominio.Caja.DenominacionCierre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoCaja")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoSucursal")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal?>("Denominacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MetodoPagoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TurnoCajaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("TurnoCajaId");

                    b.ToTable("DenominacionesCierre", "caja");
                });

            modelBuilder.Entity("SaborByte.Dominio.Caja.DenominacionEfectivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Valor")
                        .IsUnique();

                    b.ToTable("DenominacionesEfectivo", "caja");
                });

            modelBuilder.Entity("SaborByte.Dominio.Caja.MovimientoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FacturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MetodoPagoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid>("TurnoCajaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("TurnoCajaId");

                    b.ToTable("MovimientosCaja", "caja");
                });

            modelBuilder.Entity("SaborByte.Dominio.Caja.PorcentajePropina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Valor")
                        .IsUnique();

                    b.ToTable("PorcentajesPropina", "caja");
                });

            modelBuilder.Entity("SaborByte.Dominio.Caja.TurnoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CajaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoCaja")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoSucursal")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoAperturaEfectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroTurno"));

                    b.Property<Guid>("UsuarioAperturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioCierreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CajaId")
                        .IsUnique()
                        .HasFilter("[Estado] = 0");

                    b.HasIndex("NumeroTurno")
                        .IsUnique();

                    b.ToTable("TurnosCaja", "caja");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ActualizadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categorias", "catalogo");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.CodigoBarraProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarra");

                    b.HasIndex("ProductoId");

                    b.ToTable("CodigosBarraProducto", "catalogo");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.ComboItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("ComboId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoIncluidoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("ProductoIncluidoId");

                    b.ToTable("ComboItems", "catalogo");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.MetodoPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsEfectivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiereComprobante")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MetodosPago", "catalogo");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ActualizadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CostoUnitario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsCombo")
                        .HasColumnType("bit");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inventariable")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TasaItbis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0.18m);

                    b.Property<int>("TipoProducto")
                        .HasColumnType("int");

                    b.Property<Guid>("UnidadMedidaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Productos", "catalogo");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.ProductoIngrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadUsada")
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IncluidoPorDefecto")
                        .HasColumnType("bit");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Opcional")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoIngredientes", "catalogo");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.StockSucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("StockMaximo")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("StockMinimo")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId", "SucursalId")
                        .IsUnique();

                    b.ToTable("StockSucursal", "catalogo");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.UnidadMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("UnidadesMedida", "catalogo");
                });

            modelBuilder.Entity("SaborByte.Dominio.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsGenerico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NombreORazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RncOCedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoCliente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId", "RncOCedula")
                        .IsUnique()
                        .HasFilter("[RncOCedula] IS NOT NULL");

                    b.ToTable("Clientes", "clientes");
                });

            modelBuilder.Entity("SaborByte.Dominio.Comun.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("LogsAuditoria", "comun");
                });

            modelBuilder.Entity("SaborByte.Dominio.CxcCxp.CuentaPorCobrar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CuentasPorCobrar", "cxccxp");
                });

            modelBuilder.Entity("SaborByte.Dominio.CxcCxp.CuentaPorPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentoReferencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CuentasPorPagar", "cxccxp");
                });

            modelBuilder.Entity("SaborByte.Dominio.CxcCxp.PagoCxC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AnuladoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CuentaPorCobrarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MetodoPagoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaPorCobrarId");

                    b.HasIndex("MetodoPagoId");

                    b.ToTable("PagosCxC", "cxccxp");
                });

            modelBuilder.Entity("SaborByte.Dominio.CxcCxp.PagoCxP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AnuladoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CuentaPorPagarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MetodoPagoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaPorPagarId");

                    b.HasIndex("MetodoPagoId");

                    b.ToTable("PagosCxP", "cxccxp");
                });

            modelBuilder.Entity("SaborByte.Dominio.CxcCxp.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreORazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rnc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores", "cxccxp");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CajaCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CajaTurnoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClienteRncOCedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoSeguridadDgii")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<Guid?>("ComandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstadoDgii")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvioDgii")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuestaDgii")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Itbis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MensajeDgii")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("NumeroNcf")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Propina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SucursalCodigo")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoComprobante")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackIdDgii")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("XmlFirmadoDgii")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroFactura")
                        .IsUnique()
                        .HasFilter("[NumeroFactura] IS NOT NULL");

                    b.ToTable("Facturas", "facturacion");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.FacturaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CantidadAcreditada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Itbis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TasaItbis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("FacturaDetalles", "facturacion");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.FacturaPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MetodoPagoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("MetodoPagoId");

                    b.ToTable("FacturaPagos", "facturacion");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.MotivoNotaCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MotivosNotaCredito", "facturacion");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.NotaCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EstadoDgii")
                        .HasColumnType("int");

                    b.Property<Guid>("FacturaOriginalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("MotivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumeroNcf")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumeroNota")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoComprobante")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("MotivoId");

                    b.HasIndex("NumeroNota")
                        .IsUnique()
                        .HasFilter("[NumeroNota] IS NOT NULL");

                    b.ToTable("NotasCredito", "facturacion");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.NotaCreditoDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("FacturaDetalleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("NotaCreditoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FacturaDetalleId");

                    b.HasIndex("NotaCreditoId");

                    b.ToTable("NotasCreditoDetalle", "facturacion");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.SecuenciaNcf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ActualizadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<long>("SecuenciaFinal")
                        .HasColumnType("bigint");

                    b.Property<long>("SecuenciaInicial")
                        .HasColumnType("bigint");

                    b.Property<long>("SecuenciaProxima")
                        .HasColumnType("bigint");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("SecuenciasNcf", "facturacion");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.AutorizacionSupervisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Expira")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Usada")
                        .HasColumnType("bit");

                    b.Property<Guid>("UsuarioAutorizanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AutorizacionesSupervisor", "identidad");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permisos", "identidad");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", "identidad");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermisos", "identidad");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.SesionActiva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaActividad")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FechaCierre");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionesActivas", "identidad");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ActualizadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", "identidad");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles", "identidad");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.UsuarioSucursal", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "SucursalId");

                    b.HasIndex("SucursalId");

                    b.ToTable("UsuarioSucursales", "identidad");
                });

            modelBuilder.Entity("SaborByte.Dominio.Inventario.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("CostoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SaldoResultante")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MovimientosInventario", "inventario");
                });

            modelBuilder.Entity("SaborByte.Dominio.Pedidos.Comanda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<Guid?>("MesaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MeseroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreMesero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSalon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroComanda"));

                    b.Property<string>("NumeroMesa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId", "NumeroComanda")
                        .IsUnique();

                    b.ToTable("Comandas", "pedidos");
                });

            modelBuilder.Entity("SaborByte.Dominio.Pedidos.ComandaCancelacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanceladoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComandaItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InventarioRevertido")
                        .HasColumnType("bit");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RolQueCancelo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComandaCancelaciones", "pedidos");
                });

            modelBuilder.Entity("SaborByte.Dominio.Pedidos.ComandaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("InventarioDescontado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("ComandaItems", "pedidos");
                });

            modelBuilder.Entity("SaborByte.Dominio.Pedidos.ComandaItemIngrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComandaItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreIngrediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComandaItemId");

                    b.ToTable("ComandaItemIngredientes", "pedidos");
                });

            modelBuilder.Entity("SaborByte.Dominio.Pedidos.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Salon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Mesas", "pedidos");
                });

            modelBuilder.Entity("SaborByte.Dominio.Sucursales.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rnc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Empresas", "sucursales");
                });

            modelBuilder.Entity("SaborByte.Dominio.Sucursales.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ActualizadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EcfActivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ModuloCocinaActivo")
                        .HasColumnType("bit");

                    b.Property<bool>("ModuloMeseroActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("ProximoNumeroNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<bool>("SmtpActivo")
                        .HasColumnType("bit");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SmtpPuerto")
                        .HasColumnType("int");

                    b.Property<string>("SmtpRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SmtpUsaSsl")
                        .HasColumnType("bit");

                    b.Property<string>("SmtpUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("[Codigo] IS NOT NULL");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Sucursales", "sucursales");
                });

            modelBuilder.Entity("SaborByte.Dominio.Caja.DenominacionCierre", b =>
                {
                    b.HasOne("SaborByte.Dominio.Catalogo.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaborByte.Dominio.Caja.TurnoCaja", "TurnoCaja")
                        .WithMany("DenominacionesCierre")
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("TurnoCaja");
                });

            modelBuilder.Entity("SaborByte.Dominio.Caja.MovimientoCaja", b =>
                {
                    b.HasOne("SaborByte.Dominio.Catalogo.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaborByte.Dominio.Caja.TurnoCaja", "TurnoCaja")
                        .WithMany("Movimientos")
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("TurnoCaja");
                });

            modelBuilder.Entity("SaborByte.Dominio.Caja.TurnoCaja", b =>
                {
                    b.HasOne("SaborByte.Dominio.Caja.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caja");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.CodigoBarraProducto", b =>
                {
                    b.HasOne("SaborByte.Dominio.Catalogo.Producto", "Producto")
                        .WithMany("CodigosBarra")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.ComboItem", b =>
                {
                    b.HasOne("SaborByte.Dominio.Catalogo.Producto", "Combo")
                        .WithMany("ComponentesCombo")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaborByte.Dominio.Catalogo.Producto", "ProductoIncluido")
                        .WithMany()
                        .HasForeignKey("ProductoIncluidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("ProductoIncluido");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.Producto", b =>
                {
                    b.HasOne("SaborByte.Dominio.Catalogo.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.ProductoIngrediente", b =>
                {
                    b.HasOne("SaborByte.Dominio.Catalogo.Producto", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaborByte.Dominio.Catalogo.Producto", "Producto")
                        .WithMany("Receta")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.StockSucursal", b =>
                {
                    b.HasOne("SaborByte.Dominio.Catalogo.Producto", "Producto")
                        .WithMany("StockPorSucursal")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SaborByte.Dominio.CxcCxp.PagoCxC", b =>
                {
                    b.HasOne("SaborByte.Dominio.CxcCxp.CuentaPorCobrar", "Cuenta")
                        .WithMany("Pagos")
                        .HasForeignKey("CuentaPorCobrarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaborByte.Dominio.Catalogo.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("SaborByte.Dominio.CxcCxp.PagoCxP", b =>
                {
                    b.HasOne("SaborByte.Dominio.CxcCxp.CuentaPorPagar", "Cuenta")
                        .WithMany("Pagos")
                        .HasForeignKey("CuentaPorPagarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaborByte.Dominio.Catalogo.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.FacturaDetalle", b =>
                {
                    b.HasOne("SaborByte.Dominio.Facturacion.Factura", "Factura")
                        .WithMany("Detalle")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.FacturaPago", b =>
                {
                    b.HasOne("SaborByte.Dominio.Facturacion.Factura", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaborByte.Dominio.Catalogo.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.NotaCredito", b =>
                {
                    b.HasOne("SaborByte.Dominio.Facturacion.MotivoNotaCredito", null)
                        .WithMany()
                        .HasForeignKey("MotivoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.NotaCreditoDetalle", b =>
                {
                    b.HasOne("SaborByte.Dominio.Facturacion.FacturaDetalle", "FacturaDetalle")
                        .WithMany()
                        .HasForeignKey("FacturaDetalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaborByte.Dominio.Facturacion.NotaCredito", "Nota")
                        .WithMany("Detalle")
                        .HasForeignKey("NotaCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacturaDetalle");

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.RolPermiso", b =>
                {
                    b.HasOne("SaborByte.Dominio.Identidad.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaborByte.Dominio.Identidad.Rol", "Rol")
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.SesionActiva", b =>
                {
                    b.HasOne("SaborByte.Dominio.Identidad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.UsuarioRol", b =>
                {
                    b.HasOne("SaborByte.Dominio.Identidad.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaborByte.Dominio.Identidad.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.UsuarioSucursal", b =>
                {
                    b.HasOne("SaborByte.Dominio.Sucursales.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaborByte.Dominio.Identidad.Usuario", "Usuario")
                        .WithMany("SucursalesAsignadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaborByte.Dominio.Pedidos.ComandaItem", b =>
                {
                    b.HasOne("SaborByte.Dominio.Pedidos.Comanda", "Comanda")
                        .WithMany("Items")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("SaborByte.Dominio.Pedidos.ComandaItemIngrediente", b =>
                {
                    b.HasOne("SaborByte.Dominio.Pedidos.ComandaItem", null)
                        .WithMany("IngredientesExcluidos")
                        .HasForeignKey("ComandaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaborByte.Dominio.Sucursales.Sucursal", b =>
                {
                    b.HasOne("SaborByte.Dominio.Sucursales.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SaborByte.Dominio.Caja.TurnoCaja", b =>
                {
                    b.Navigation("DenominacionesCierre");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SaborByte.Dominio.Catalogo.Producto", b =>
                {
                    b.Navigation("CodigosBarra");

                    b.Navigation("ComponentesCombo");

                    b.Navigation("Receta");

                    b.Navigation("StockPorSucursal");
                });

            modelBuilder.Entity("SaborByte.Dominio.CxcCxp.CuentaPorCobrar", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SaborByte.Dominio.CxcCxp.CuentaPorPagar", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.Factura", b =>
                {
                    b.Navigation("Detalle");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SaborByte.Dominio.Facturacion.NotaCredito", b =>
                {
                    b.Navigation("Detalle");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.Rol", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("SaborByte.Dominio.Identidad.Usuario", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("SucursalesAsignadas");
                });

            modelBuilder.Entity("SaborByte.Dominio.Pedidos.Comanda", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SaborByte.Dominio.Pedidos.ComandaItem", b =>
                {
                    b.Navigation("IngredientesExcluidos");
                });
#pragma warning restore 612, 618
        }
    }
}
